# Generated by Django 6.0.1 on 2026-01-18 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bags', models.IntegerField(default=0)),
                ('current_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.godown')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SR', 'Stock Register (Incoming)'), ('DL', 'Deposit Ledger (Outgoing)')], max_length=2)),
                ('bags', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.godown')),
            ],
        ),
    ]
