# Generated by Django 6.0.1 on 2026-01-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(default='General', help_text='Name of Farmer or Buyer', max_length=100, verbose_name='Person Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SR', 'Stock Register (Incoming)'), ('DL', 'Delivery (Outgoing)')], max_length=2),
        ),
    ]
