# Generated by Django 6.0.1 on 2026-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_transaction_party_name_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.CharField(default='Main Branch', max_length=100, verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='crop_year',
            field=models.CharField(default='2025-26', max_length=20, verbose_name='Crop Year'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='district',
            field=models.CharField(default='Seoni', max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(default='General', max_length=100, verbose_name='Person Name'),
        ),
    ]
