# Generated by Django 6.0.1 on 2026-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transaction_branch_transaction_crop_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='type',
            field=models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], default='Rabi', max_length=50),
        ),
        migrations.AddField(
            model_name='godown',
            name='capacity',
            field=models.IntegerField(default=10000, help_text='Total Bags Capacity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='gate_pass',
            field=models.CharField(blank=True, help_text='Gate Pass (Delivery)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hamar_labor',
            field=models.CharField(blank=True, help_text='Labor Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shortage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Loss/Shortage', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stack_no',
            field=models.CharField(blank=True, help_text='Stack No (Deposit)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='truck_number',
            field=models.CharField(blank=True, help_text='Truck No (Delivery)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='party_name',
            field=models.CharField(default='General', max_length=100, verbose_name='Person/Party Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SR', 'Stock Receipt (Deposit)'), ('DL', 'Delivery (Outgoing)')], max_length=2),
        ),
        migrations.DeleteModel(
            name='StockBalance',
        ),
    ]
